# -*- coding: utf-8 -*-
"""brain_tumor_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-u1N-SgrHsXPQk83U4LttWgBa7spzslj
"""
import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image

# Load model
model = tf.keras.models.load_model("Brain_Tumor_Detection/README.md")

st.title("Image Classification App")

# Upload image
uploaded_file = st.file_uploader("Upload an image", type=["jpg", "png", "jpeg"])

if uploaded_file is not None:
    image = Image.open(uploaded_file).convert("RGB")
    st.image(image, caption="Uploaded Image", use_column_width=True)

    # Preprocess image (change size based on your model)
    img = image.resize((224, 224))
    img_array = np.array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    # Predict
    prediction = model.predict(img_array)

    class_index = np.argmax(prediction)
    confidence = np.max(prediction)

    st.success(f"Prediction: Class {class_index}")
    st.info(f"Confidence: {confidence:.2f}")
