"""app_fraud.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18tBZNyA7FvmzFZjsg40eiIQeYECoBHPn
"""
import streamlit as st
import numpy as np
import pickle

# -----------------------------------
# Load trained files
# -----------------------------------
model = pickle.load(open("Online_Fraud_Detection/fraud_detect.pkl", "rb"))
scaler = pickle.load(open("Online_Fraud_Detection/scaler_fraud.pkl", "rb"))
encoders = pickle.load(open("Online_Fraud_Detection/encoders_fraud.pkl", "rb"))


# -----------------------------------
# App UI
# -----------------------------------
st.set_page_config(page_title="Online Fraud Detection", layout="centered")
st.title("💳 Online Payment Fraud Detection System")

st.write("Enter transaction details to predict whether it is fraudulent.")

# -----------------------------------
# User Inputs
# -----------------------------------
amount = st.number_input("Transaction Amount", min_value=0.0, step=1.0)

transaction_type = st.selectbox(
    "Transaction Type",
    encoders["Transaction_Type"].classes_
)

device = st.selectbox(
    "Device Used",
    encoders["Device_Used"].classes_
)

payment = st.selectbox(
    "Payment Method",
    encoders["Payment_Method"].classes_
)

location = st.selectbox(
    "Location",
    encoders["Location"].classes_
)

# -----------------------------------
# Prediction
# -----------------------------------
if st.button("Predict Fraud"):

    # Encode inputs
    t_type_enc = encoders["Transaction_Type"].transform([transaction_type])[0]
    device_enc = encoders["Device_Used"].transform([device])[0]
    payment_enc = encoders["Payment_Method"].transform([payment])[0]
    location_enc = encoders["Location"].transform([location])[0]

    user_input = np.array(
        [[amount, t_type_enc, device_enc, payment_enc, location_enc]]
    )

    # Scale
    user_scaled = scaler.transform(user_input)

    # Predict
    fraud_prob = model.predict_proba(user_scaled)[0][1]

    # Output
    if fraud_prob > 0.5:
        st.error(f"🚨 Fraudulent Transaction\n\nProbability: {fraud_prob:.2f}")
    else:
        st.success(f"✅ Safe Transaction\n\nProbability: {1 - fraud_prob:.2f}")
